---
# Implements CIS OpenShift Control 3.1.1
kind: Rule
checkType: Platform
title: Verify at least one identity provider has been configured
expression: identityProvider.spec.identityProviders.size() >= 1
inputs:
  - name: identityProvider
    type: KubeGroupVersionResource
    apiGroup: config.openshift.io
    version: v1
    resource: oauths
    subResource: cluster
