---
# Implements CIS OpenShift Control 3.1.1
kind: Rule
checkType: Platform
title: Verify at least one identity provider has been configured
expression: cluster.spec.identityProviders.size() >= 1
inputs:
    # namespace : type : resource
  - openshift-authentication:oauth:cluster
